config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  
  get 'about', to: 'pages#about'
  
  get 'signup', to: 'users#new'
  
  resources :users, except: [:new]
  resources :articles

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :categories, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	has_many :article_categories
	has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimum: 3, maximum: 50 }
	validates :description, presence:true, length: { minimum: 10, maximum: 300 }
	validates :user_id, presence: true
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  before_save { self.email = email.downcase }
  validates :username, presence: true, 
  					uniqueness: { case_sensitive: false }, 
            length: { minimum: 3, maximum:25 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 },
            uniqueness: { case_sensitive:false },
            format: { with: VALID_EMAIL_REGEX }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising exception.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = "You must be logged in to perform that action"
      redirect_to root_path
    end
  end


end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	before_action :set_article, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@articles = Article.paginate(page: params[:page], per_page: 5)
	end

	def new
    @article = Article.new
	end

	def edit 
	end

	def create
		@article = Article.new(article_params)
		@article.user = current_user
		if @article.save
			flash[:success] = "Article Created!"
			redirect_to article_path(@article)
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:success] = "Article Updated!"
			redirect_to article_path(@article)
		else
			render 'edit'
		end
	end

	def show
	end

	def destroy
		@article.destroy
		flash[:danger] = "Article Deleted!"
		redirect_to articles_path
	end

	private
		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description, category_ids: [])
		end

		def require_same_user
			if current_user != @article.user and !current_user.admin?
				flash[:danger] = "You can only edit or delete your own articles"
				redirect_to root_path
			end
		end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_admin, except: [:index, :show]
 
  def index
    @categories = Category.paginate(page: params[:page], per_page: 5)
  end

  def new
   @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Category was created successfully"
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "Category name was successfuly updated"
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end

  
  def show
    @category = Category.find(params[:id])
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 5)
  end
  
  private
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !logged_in? || (logged_in? and !current_user.admin?)
      flash[:danger] = "Only admin can perform that action"
      redirect_to categories_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def home
		redirect_to articles_path if logged_in?
	end

	def about

	end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  
  end

  def create
    # render 'new'
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to user_path(user)
    else
      flash.now[:danger] = "There was something wrong with your login information"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to root_path
  end 

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]
	before_action :require_admin, only: [:destroy]
	
	def index
		@users = User.paginate(page: params[:page], per_page: 5)
	end
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome To The Alpha Blog #{@user.username}"
			redirect_to users_path(@user)
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @user.update(user_params)
			flash[:success] = "Account Updated"
			redirect_to articles_path
		else
			render 'edit'
		end
	end

	def show
		@user_articles = @user.articles.paginate(page: params[:page], per_page: 5)
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		flash[:danger] = "User and all articles created by user have been deleted"
		redirect_to users_path
	end

	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user and !current_user.admin?
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end
	end
	
	def require_admin
		if logged_in? and !current_user.admin?
			flash[:danger] = "Only admin users can perform that action"
			redirect_to root_path
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.username, class: "rounded-circle")
	end
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
	<div class="card mb-3">
		<div class="card-body">
			<div class="article-title">
				<%= link_to article.title, article_path(article) %>
			</div>
			<div class="article-body">
				<%= truncate(article.description, length: 150) %>
			</div>
			<% if article.categories.any? %>
				<p>Categories: <%= render article.categories %></p>

			<% end %>
			<% if logged_in? && (current_user == article.user || current_user.admin?) %>
				<div class="article-actions">
					<%= link_to "Edit This Article", edit_article_path(article), class: "btn btn-xs btn-primary" %> 
					<%= link_to "Delete This Article", article_path(article), method: :delete, 
																																		data: { confirm: "Are You Sure?" }, 
																																		class: "btn btn-xs btn-danger" %>
				</div>
			<% end %>
		</div>
	</div>
<% end %>

app/views/articles/_form.html.erb
<div class="container">
	<%= render 'shared/errors', obj: @article %>
	<div class="row">
		<div class="col-md-12">
			<%= form_for @article do |f| %>
				<div class="form-group">
					<%= f.label :title %>
					<%= f.text_field :title, class: "form-control", placeholder: "Title of article", autofocus:true %><br>
					<%= f.label :description %>
					<%= f.text_area :description, class: "form-control", placeholder: "Body of the article" %><br>
					<div class="row">
						<div class="col-sm-offset-2 col-sm-8">
						<%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
							<% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>	
						<% end %>
						</div>
					</div>
					<%= f.submit class: "btn btn-primary" %><br>
			<% end %>
			<br>
			<%= link_to "(Cancel)", articles_path %>
				</div>
		</div>
	</div>
</div>

app/views/articles/edit.html.erb
<h1 class="headings">
    <center>
        Edit Article
    </center>
</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<div class="container">
	<h1 class="headings">
		<center>
				Listing All Articles
		</center>
	</h1>
	<br>
	<div class="d-flex justify-content-center">
		<%= will_paginate %>
	</div>
	<%= render 'article' , obj: @articles%>
	<div class="d-flex justify-content-center">
		<%= will_paginate %>
	</div>
</div>

app/views/articles/new.html.erb
<h1 class="headings">
    <center>
        Create An Article
    </center>
</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="container">
  <h2 class="headings">
    <center>
        Title: <%= @article.title %>
    </center>
  </h2>
  <center>
  <center>
  <% if @article.user %>
    <ul class="listing">
      <div class="card mb-3">
        <div class="card-body">
          <li>Created by: </li>
          <li><%= link_to gravatar_for(@article.user), user_path(@article.user) %></li>
          <li class="article-title">
            <%= link_to @article.user.username, user_path(@article.user) %>
          </li>
          <li>
            <small>
              <%= pluralize(@article.user.articles.count, "article") if @article.user.articles %>
            </small>
          </li>
        </div>
      </div>
    </ul>	
  <% end %>
  </center>
  <div class="card col-xs-8 col-xs-offset-2">
    <div class="card-body">
      <h4 class="card-title">Description:</h4>
      <hr>
      <p><%= simple_format(@article.description) %></p>
      <% if @article.categories.any? %>
        <p>Categories: <%= render @article.categories %></p>

      <% end %>
      <div class="article-actions">
        <% if logged_in? && (current_user == @article.user || current_user.admin?) %>
          <%= link_to "Edit This Article", edit_article_path(@article), class: "btn btn-xs btn-primary" %> 
          <%= link_to "Delete This Article", article_path(@article), method: :delete, 
                                              data: { confirm: "Are You Sure?" }, 
                                              class: "btn btn-xs btn-danger" %>
        <% end %>
        <%= link_to "View All Articles", articles_path, class: "btn btn-xs btn-success" %>
      </div>
    </div>
  </div>
  </center>
</div>

app/views/categories/_category.html.erb
<span class="badge badge-secondary">
  <%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<%= render 'shared/errors', obj: @category %>
    
  <%= form_for @category do |f| %>
    <div class="form-group">
      <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus:true %><br>
      <%= f.submit class: "btn btn-primary" %><br>
  <% end %>
  <br>
  <%= link_to "(Cancel)", articles_path %>
    </div>

app/views/categories/edit.html.erb
<div class="container">
  <h1 class="headings">
    <center>
      Edit Category Name
    </center>
  </h1>

  <%= render 'form' %>
</div>

app/views/categories/index.html.erb
<div class="container">
  <h1 class="headings">
    <center>
      Listing All Categories
    </center>
  </h1>
  <div class="d-flex justify-content-center">
		<%= will_paginate %>
	</div>
  <% @categories.each do |category| %>
    <ul class="listing">
      <center>
        <div class="card">
          <div class="card-body">
            <h3 class="card-title"><%= link_to "#{category.name}", category_path(category) %></h3>
            <small>
              <%= pluralize(category.articles.count, "article") %>
            </small>
          </div>
        </div>
      </center>
    </ul>
  <% end %>
  <div class="d-flex justify-content-center">
		<%= will_paginate %>
	</div>
</div>

app/views/categories/new.html.erb
<div class="container">
  <h1 class="headings">
    <center>
      Create New Category
    </center>
  </h1>

  <%= render 'shared/errors', obj: @category %>
    
    <%= form_for @category do |f| %>
      <div class="form-group">
        <%= f.text_field :name, class: "form-control", placeholder: "Category name", autofocus:true %><br>
        <%= f.submit class: "btn btn-primary" %><br>
    <% end %>
    <br>
    <%= link_to "(Cancel)", articles_path %>
      </div>
</div>

app/views/categories/show.html.erb
<div class="container">
	<h1 class="headings">
		<center>
			<%= "Category: " + @category.name %>
		</center>
	</h1>
	<br>
	<% if logged_in? and current_user.admin? %>
		<div class="d-flex justify-content-center">
			<span class="badge badge-secondary">
				<%= link_to "Edit Category Name", edit_category_path(@category) %>
			</span>
		</div>
	<% end %>
	<div class="d-flex justify-content-center">
		<%= will_paginate @category_articles %>
	</div>
	<%= render 'articles/article' , obj: @category_articles%>
	<div class="d-flex justify-content-center">
		<%= will_paginate @category_articles %>
	</div>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer fixed-bottom">
	<div class="container">
		<span class="text-muted">Copyright ©2021 Made by Indraan S. Toor</span>
	</div>
</footer>

app/views/layouts/_messages.html.erb
<% if !flash.empty?%>
         <% flash.each do |name, msg| %>
          <div class='alert alert-<%= "#{name}" %> alert-dismissible fade show' role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
            <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
          </div>
        <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'Alpha Blog', root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "Articles", articles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Users", users_path, class: "nav-link" %>
      </li>
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Actions
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "New Article", new_article_path, class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "(Admin)" if current_user.admin? %>
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %>
            <%= link_to "View your profile", user_path(current_user), class: "dropdown-item" %>
          </div>
        </li>
        <li class="nav-item">
          <li><%= link_to 'Log out', logout_path, method: :delete, class: "nav-link" %></li>
        </li>
      <% else %>
        <li class="nav-item">
          <li><%= link_to 'Login', login_path, class: "nav-link" %></li>
        </li>
        <li class="nav-item">
          <li><%= link_to 'Sign up', signup_path, class: "nav-link" %></li>
        </li>
      <% end %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path, class: "dropdown-item" %>
          <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category), class: "dropdown-item" %>
          <% end %>
          <% if logged_in? and current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to "Create New Category", new_category_path %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-light">
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to 'Home', root_path %>

app/views/pages/home.html.erb
<div class="container mt-3">
  <section class="jumbotron text-center">
    <div class="container jumbotron-content">
      <h1 class="jumbotron-heading">ALPHA BLOG</h1>
      <%# <p class="lead">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> %>
      <p class="lead">Share your ideas, discoveries and thoughts with the world. Sign Up to write articles, select a category or create a new one and share it with the world. It's as simple as that!</p>
      <p>
        <%= link_to 'Log In', signup_path, class: "btn btn-primary my-2" %>
        <a href="#" class="btn btn-secondary my-2">Sign Up</a>
      </p>
    </div>
  </section>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger" role="alert">
		<div class="panel-heading">
			<h4 class="panel-title"><%= pluralize(obj.errors.count, "Error") %> Occured</h4>
				<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
					<% end %>
				</ul>
		</div>
	</div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>
<div class="row">
	<div class="col-md-12">
		<%= form_for @user do |f| %>
			<div class="form-group">
				<%= f.label :username %>
				<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:true %><br>
				<%= f.label :email %>
				<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %><br>
				<%= f.label :password %>
				<%= f.password_field :password, class: "form-control", placeholder: "Enter password" %><br>
				<%= f.submit(@user.new_record? ? "Sign up" : "Update Account", class: "btn btn-primary") %><br>
		<% end %>
		<br>
		<%= link_to "(Cancel)", articles_path %>
			</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<h1 class="headings">
		<center>
			Edit Your Account
		</center>
	</h1>
	<%= render 'form' %>
</div>

app/views/users/index.html.erb
<div class="container">
	<h1 class="headings">
		<center>
			All Alpha Bloggers
		</center>
	</h1>
	<br>
	<div class="d-flex justify-content-center">
		<%= will_paginate %>
	</div>
	<% @users.each do |user| %>
		<center>
			<ul class="listing">
				<div class="card mb-3">
					<div class="card-body">
						<li><%= link_to gravatar_for(user), user_path(user) %></li>
						<li class="article-title">
							<%= link_to user.username, user_path(user) %>
						</li>
						<li>
							<small>
								<%= pluralize(user.articles.count, "article") if user.articles %>
							</small>
						</li>
						<% if logged_in? and current_user.admin? %>
							<li>
								<%= link_to "Delete this user", user_path(user), method: :delete,
									data: { confirm: "Are you sure you want to delete the user and all their articles?" } %>
							</li>
						<% end %>
					</div>
				</div>
			</ul>	
		</center>
	<% end %>
	<div class="d-flex justify-content-center">
		<%= will_paginate %>
	</div>
</div>

app/views/users/new.html.erb
<div class="container">
	<h1 class="headings">
		<center>
			Signup For Alpha Blog
		</center>
	</h1>
	<%= render 'shared/errors', obj: @user %>
	<div class="row">
		<div class="col-md-12">
			<%= form_for @user do |f| %>
				<div class="form-group">
					<%= f.label :username %>
					<%= f.text_field :username, class: "form-control", placeholder: "Enter username", autofocus:true %><br>
					<%= f.label :email %>
					<%= f.email_field :email, class: "form-control", placeholder: "Enter email" %><br>
					<%= f.label :password %>
					<%= f.password_field :password, class: "form-control", placeholder: "Enter email" %><br>
					<%= f.submit "Sign up", class: "btn btn-primary" %><br>
			<% end %>
			<br>
			<%= link_to "(Cancel)", articles_path %>
				</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
  <h1 class="headings">
		<center>
			Welcome to <%= @user.username %>'s page
		</center>
	</h1>
	<br>
  <center>
    <ul class="listing">
      <div class="card mb-3">
        <div class="card-body">
          <li><%= gravatar_for @user %></li>
        </div>
      </div>
    </ul>

    <h4>
      <%= @user.username %>'s articles
    </h4>
    <br>
    <div class="d-flex justify-content-center">
      <%= will_paginate @user_articles %>
    </div>
    <%= render 'articles/article', obj: @user_articles %>
    <div class="d-flex justify-content-center">
      <%= will_paginate @user_articles %>
    </div>
  </center>
</div>s